### ISSUE TITLE
USER STORY: Jump to top

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Jukebox_Hackathon_WPJ#17]
As a user I can tap a button so that the website jumps to the top.

#Success Critera
1. An arrow button appears when the user has scrolled 50% down the page, past the album art section
2. User can tap on this button to jump to the search input section
3. Button is not too big at smaller screen sizes

#Tasks 
- [ ] Add arrow button in fixed location on screen
- [ ] Add js to make button disappear above 50% scroll
- [ ] Add href to link button to top of screen
