### ISSUE TITLE
USER STORY: Seaching for a song

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Jukebox_Hackathon_WPJ#2]
As a user, I can type in a song name into the search bar so I can view song details such as artist name and lyrics. 

# Success Criteria
1. A text input field will accept user input and submit a request to an API
2. The API will return the appropriate song information
3. The information will be displayed to the user on a responsive card.  

# Tasks

- [x] Set up the Input field
- [x] Set up Song Info display card/section below Input field
- [x] Integrate the genius lyric API to get the user input and return song information
- [x] Display the song information in a card below the search bar. It will remain until a new query is submitted
- [x] Update this card/container with new song information when new requests are created
- [x] Allow Enter key to submit request

**Comment by Will-WHyd** [comment]
@Patrick5009  Tasks: Song Display zone setup
@jack-brosnan  API integration

**Comment by Will-WHyd** [comment]
Added a new task here: Allow Enter key to submit request
