### ISSUE TITLE
USER STORY: Mobile and Desktop design

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Jukebox_Hackathon_WPJ#3]
As a user I can use the site on mobile, tablet, or computer, so that I'm not locked to one device when I want to listen to music.

# Success Critera
1. Website features resonsive design that adjusts based on screen size
2. Design is not cramped when on mobile or too barren on fullscreen
3. Design is attractive and modern. 

# Tasks 
- [ ] Include media queries for screen size using css & bootstrap
- [ ] Agree on style/aesthetic in more detailed wireframing discussion
- [ ] Implement style choices in html and css
