### ISSUE TITLE
USER STORY: View music video

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Jukebox_Hackathon_WPJ#5]
As a user I can input a song name so that I can view music videos of that song on youtube.

# Success Critera
1. There is an input field that sends the user's request to the Youtube API. 
2. The API presents videos in a separate panel. 
3. The user only has to enter the song name once to view both the lyrics/song info, and the music videos. 

# Tasks 
- [x] Create section for Youtube video cards/content
- [x] Create bootstrap modal to display selected videos
- [x] Integrate youtube api to fetch data at the same time/immediately following the genius API. 
- [x] Display results in Video Section 
- [x] Display Modal on click of video, displaying video.
