### ISSUE TITLE
USER STORY: Custom search filter for videos

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Jukebox_Hackathon_WPJ#6]
As a user I can filter the results of the video search so I can see other versions such as live shows or instrumentals. 

# Success Critera
1. The user can toggle radio buttons in the search results to find instrumentals/live shows/other versions of the songs.
2. The option to search videos can be turned off or hidden, in case the user only wants to view song details. 

# Tasks 
- [x] Implement radio buttons for each filter
- [x] Add event listeners to refresh the youtube api request
- [x] Add clear filter option to return to original user query
- [ ] Add 'hide section' toggle to hide visibility

**Comment by Will-WHyd** [comment]
@jack-brosnan Tackle the api integrations when prior issues cleared
